export const WS_FEED_CONNECTION_START = 'WS_FEED_CONNECTION_START' as const;
export const WS_FEED_CONNECTION_SUCCESS = 'WS_FEED_CONNECTION_SUCCESS' as const;
export const WS_FEED_CONNECTION_CLOSED = 'WS_FEED_CONNECTION_CLOSED' as const;
export const WS_FEED_CONNECTION_ERROR = 'WS_FEED_CONNECTION_ERROR' as const;
export const WS_FEED_CONNECTION_MESSAGE = 'WS_FEED_CONNECTION_MESSAGE' as const;
