export const WS_ORDERS_HISTORY_CONNECTION_START =
  'WS_ORDERS_HISTORY_CONNECTION_START';
export const WS_ORDERS_HISTORY_CONNECTION_SUCCESS =
  'WS_ORDERS_HISTORY_CONNECTION_SUCCESS';
export const WS_ORDERS_HISTORY_CONNECTION_CLOSED =
  'WS_ORDERS_HISTORY_CONNECTION_CLOSED';
export const WS_ORDERS_HISTORY_CONNECTION_ERROR =
  'WS_ORDERS_HISTORY_CONNECTION_ERROR';
export const WS_ORDERS_HISTORY_CONNECTION_MESSAGE =
  'WS_ORDERS_HISTORY_CONNECTION_MESSAGE';
