export const WS_ORDERS_HISTORY_CONNECTION_START =
  'WS_ORDERS_HISTORY_CONNECTION_START' as const;
export const WS_ORDERS_HISTORY_CONNECTION_SUCCESS =
  'WS_ORDERS_HISTORY_CONNECTION_SUCCESS' as const;
export const WS_ORDERS_HISTORY_CONNECTION_CLOSED =
  'WS_ORDERS_HISTORY_CONNECTION_CLOSED' as const;
export const WS_ORDERS_HISTORY_CONNECTION_ERROR =
  'WS_ORDERS_HISTORY_CONNECTION_ERROR' as const;
export const WS_ORDERS_HISTORY_CONNECTION_MESSAGE =
  'WS_ORDERS_HISTORY_CONNECTION_MESSAGE' as const;
